name: '[🔨] Build'
run-name: '[🔨] Build - ${{ github.head_ref }}'
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - name: Build
        run: npm run build
