name: '[😱] Checkin'
run-name: '[😱] Checkin - ${{ github.head_ref }}'
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  Style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - name: Lint
        run: npx nx run-many --target lint --no-cache
      - name: Format
        run: npx nx format:check
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - name: Build
        run: npm run build
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - name: Test
        run: npx nx run-many --target test --all --no-cache
