name: '[🔨] Checkin'
run-name: '[🔨] Checkin: ${{ github.head_ref }}'
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup NX
        uses: nrwl/nx-set-shas@v3
      - name: Check NPM Packages
        run: npm ci
      - name: Test
        run: npx nx run-many --target test
