name: '[😱] Checkin'
run-name: '[😱] Checkin - ${{ github.head_ref }}'
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  Checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
