name: '[😱] Checkin'
run-name: '[😱] Checkin - ${{ github.head_ref }}'
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: .github/workflows/build.yml
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - name: Test
        run: npm run test
