name: '[🎨] Style Checker'
run-name: '[🎨] Style Checker: ${{ github.head_ref }}'
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: nrwl/nx-set-shas@v3
      - name: Verify Packages
        run: npm ci
      - name: Lint
        run: npx nx run-many --target lint
